# ESXi Commander Configuration Example
# Copy this file to ~/.ceso/config.yaml and update with your values

# ESXi Connection Settings
esxi:
  host: "192.168.1.100"      # ESXi host IP or hostname
  user: "root"                # ESXi username
  password: ""                # ESXi password (use environment variable ESXI_PASSWORD for security)
  insecure: true              # Allow self-signed certificates
  timeout: 30s                # Connection timeout

# Default VM Settings
vm:
  defaults:
    cpu: 2                    # Default vCPUs for new VMs
    memory: 4096              # Default memory in MB
    disk: 20                  # Default disk size in GB
    template: "ubuntu-22.04"  # Default VM template
    
  # Network configuration
  network:
    subnet: "192.168.1.0/24"  # Default subnet for VMs
    gateway: "192.168.1.1"    # Default gateway
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    domain: "local"           # DNS domain

# Backup Configuration
backup:
  catalog_path: "~/.ceso/backup.db"  # BoltDB catalog location
  default_target: "datastore"        # Backup target: datastore, nfs, s3
  compression: "gzip"                # Compression: none, gzip, zstd
  temp_dir: "/tmp/ceso-backup"       # Temporary directory for backups
  
  # Retention policy
  retention:
    keep_last: 5              # Keep last N backups per VM
    keep_daily: 7             # Keep daily backups for N days
    keep_weekly: 4            # Keep weekly backups for N weeks
    keep_monthly: 12          # Keep monthly backups for N months
  
  # Datastore target settings
  datastore:
    name: "datastore1"        # Datastore name
    path: "/backups"          # Path within datastore

# Security Settings
security:
  mode: "standard"            # Operation mode: restricted, standard, unrestricted
  audit_log: "~/.ceso/audit.json"  # Audit log location
  
  # IP allowlist (optional)
  ip_allowlist:
    enabled: false
    allowed:
      - "192.168.1.0/24"
      - "10.0.0.0/8"
  
  # AI Agent specific settings
  ai_agent:
    default_mode: "restricted"  # Default mode for AI agents
    promotion_timeout: "1h"     # Maximum promotion duration
    require_human_approval: true  # Require approval for promotions

# Monitoring Configuration
metrics:
  enabled: true               # Enable Prometheus metrics
  port: 9090                  # Metrics port
  path: "/metrics"            # Metrics endpoint path
  
  # Metric labels
  labels:
    environment: "production"
    datacenter: "dc1"
    cluster: "esxi-prod"

# Performance Settings
performance:
  # Connection pool settings
  connection_pool:
    enabled: true
    min_connections: 2        # Minimum pool size
    max_connections: 10       # Maximum pool size
    max_idle_time: "5m"       # Maximum idle time
    health_check_interval: "30s"  # Health check frequency
  
  # Operation timeouts
  timeouts:
    vm_create: "5m"           # VM creation timeout
    vm_clone: "10m"           # VM clone timeout
    backup_create: "30m"      # Backup creation timeout
    backup_restore: "30m"     # Backup restore timeout

# Logging Configuration
logging:
  level: "info"               # Log level: debug, info, warn, error
  format: "json"              # Log format: json, text
  output: "stdout"            # Output: stdout, file
  file: "~/.ceso/ceso.log"    # Log file path (if output=file)
  
  # Log rotation (if output=file)
  rotation:
    max_size: "100MB"         # Maximum file size
    max_age: "30d"            # Maximum age
    max_backups: 10           # Maximum number of backups
    compress: true            # Compress rotated logs

# Template Management
templates:
  refresh_interval: "1h"      # Template list refresh interval
  
  # Template sources
  sources:
    - name: "local"
      type: "datastore"
      path: "/templates"
    
    # Future: OVA repository
    # - name: "repository"
    #   type: "http"
    #   url: "https://templates.example.com"

# Advanced Settings
advanced:
  # SSH fallback configuration
  ssh:
    enabled: true             # Enable SSH fallback
    port: 22                  # SSH port
    timeout: "30s"            # SSH command timeout
    max_retries: 3            # Maximum retry attempts
  
  # Resource allocation
  resources:
    cpu_overcommit: 2.0       # CPU overcommit ratio
    memory_overcommit: 1.5    # Memory overcommit ratio
    
  # VM naming
  naming:
    pattern: "{prefix}-{timestamp}"  # VM naming pattern
    prefix: "vm"              # Default prefix
    timestamp_format: "20060102-1504"  # Timestamp format

# Environment-specific overrides
# Use these to override settings per environment
environments:
  development:
    esxi:
      host: "192.168.1.50"
    security:
      mode: "unrestricted"
    logging:
      level: "debug"
  
  staging:
    esxi:
      host: "192.168.1.75"
    security:
      mode: "standard"
  
  production:
    esxi:
      host: "192.168.1.100"
    security:
      mode: "restricted"
    backup:
      retention:
        keep_monthly: 24