templates:
  ubuntu-22.04-lts:
    name: "Ubuntu 22.04 LTS"
    description: "Ubuntu 22.04 LTS Server template with cloud-init"
    os: "ubuntu64Guest"
    min_cpu: 1
    min_ram: 2
    min_disk: 20
    cloud_init_required: true
    vmware_tools_required: true
  
  ubuntu-20.04-lts:
    name: "Ubuntu 20.04 LTS"
    description: "Ubuntu 20.04 LTS Server template with cloud-init"
    os: "ubuntu64Guest"
    min_cpu: 1
    min_ram: 2
    min_disk: 20
    cloud_init_required: true
    vmware_tools_required: true